fbrv.shift <- function(data,x,y,expand=0){
  # data is a to be shifted set of coordinates for a single factor as generated by fbrv.model
  # x is the x-shift, y is the y-shift to be applied
  # if expand is T, the shift will be much different as to make room for correlation labels
  
  # stripping off superfluous information
  data_shifted <- data[c("cart_circles",
                         "cart_axes",
                         "axis_tick",
                         "axis_tick_label",
                         "subfactor_cor_arrows",
                         "subfactor_cor_labels",
                         "factor_label",
                         "inner_cors")]
  data_shifted$axis_tick[1:2] <- list(NULL)
  data_shifted$subfactor_cor_arrows <- data_shifted$subfactor_cor_arrows[,c("x1","y1","x2","y2")]
  
  # changing the shift to expand the circle, making room for correlation labels
  if(expand!=0){
    ynew <- y+sqrt(expand^2/(x/y+1))
    x <- x+sqrt(expand^2/(y/x+1))
    y <- ynew
    rm(ynew)
  }
  
  # adding x shift
  data_shifted$cart_circles$x <- data_shifted$cart_circles$x+x
  data_shifted$cart_axes$x0 <- data_shifted$cart_axes$x0+x
  data_shifted$cart_axes$x1 <- data_shifted$cart_axes$x1+x
  data_shifted$cart_axes$x2 <- data_shifted$cart_axes$x2+x
  data_shifted$cart_axes$x3 <- data_shifted$cart_axes$x3+x
  data_shifted$axis_tick$x <- data_shifted$axis_tick$x+x
  data_shifted$axis_tick$x1 <- data_shifted$axis_tick$x1+x
  data_shifted$axis_tick$x2 <- data_shifted$axis_tick$x2+x
  data_shifted$axis_tick_label$x <- data_shifted$axis_tick_label$x+x
  data_shifted$subfactor_cor_arrows$x1 <- data_shifted$subfactor_cor_arrows$x1+x
  data_shifted$subfactor_cor_arrows$x2 <- data_shifted$subfactor_cor_arrows$x2+x
  data_shifted$subfactor_cor_labels$x <- data_shifted$subfactor_cor_labels$x+x
  data_shifted$factor_label$x <- data_shifted$factor_label$x+x
  data_shifted$inner_cors$x <- data_shifted$inner_cors$x+x
  
  # adding y shift
  data_shifted$cart_circles$y <- data_shifted$cart_circles$y+y
  data_shifted$cart_axes$y0 <- data_shifted$cart_axes$y0+y
  data_shifted$cart_axes$y1 <- data_shifted$cart_axes$y1+y
  data_shifted$cart_axes$y2 <- data_shifted$cart_axes$y2+y
  data_shifted$cart_axes$y3 <- data_shifted$cart_axes$y3+y
  data_shifted$axis_tick$y <- data_shifted$axis_tick$y+y
  data_shifted$axis_tick$y1 <- data_shifted$axis_tick$y1+y
  data_shifted$axis_tick$y2 <- data_shifted$axis_tick$y2+y
  data_shifted$axis_tick_label$y <- data_shifted$axis_tick_label$y+y
  data_shifted$subfactor_cor_arrows$y1 <- data_shifted$subfactor_cor_arrows$y1+y
  data_shifted$subfactor_cor_arrows$y2 <- data_shifted$subfactor_cor_arrows$y2+y
  data_shifted$subfactor_cor_labels$y <- data_shifted$subfactor_cor_labels$y+y
  data_shifted$factor_label$y <- data_shifted$factor_label$y+y
  data_shifted$inner_cors$y <- data_shifted$inner_cors$y+y
  
  return(data_shifted)
  
}