#' Plot Items
#' 
#' This function plots a factor and its items as bars on radial axes representing its facets.
#'
#' @param coor list generated by \code{\link{model_items}} or \code{\link{model_nested}} containing the coordinates of the parts of the plot.
#' @param size integer; smartly scaled size of all parts of the plot.
#' @param filename character string; name of the .pdf file the plot is written to; filename extension adds automatically.
#' @param width integer; width of the .pdf file; defaults to 10.
#' @param height integer; height of the .pdf file; defaults to 10.
#' @param font character; text font; defaults to 'Helvetica'.
#' @param colour character; name of the accent colour.
#' @param colour2 character; name of the second accent colour used to better distinguish between similar items
#' @param tick_label logical; if TRUE, plots a text label for the axis tick
#' @param size_title integer; font size of the factor label (relative to default).
#' @param size_axis_labels integer; font size of the axis labels (relative to default).
#' @param width_axes integer; width of the radial axis lines (relative to default).
#' @param size_arrow_heads integer; length of the arrow heads (relative to default).
#' @param width_items integer; width of the item bars (relative to default). Currently not supported!
#' @param size_grid integer; width of the dotted grid lines (relative to default).
#' @param size_tick_label integer; font size of the axis tick label (relative to default).
#' @param size_center_dot integer; size of the center dot marking the origin (relative to default).
#'
#' @return an object of the class "ggplot" and the same object as a .pdf file.
#'  
#' @export
plot_items <- function(coor,size=1,filename,
                            width=10,height=10,font="serif",
                            colour="black",colour2="black",tick_label=TRUE,
                            size_title=1,size_axis_labels=1,width_axes=1,size_arrow_heads=1,width_items=1,size_grid=1,size_tick_label=1,size_center_dot=1){
  
  graphics.off()
  
  # plot layers
  myfbrv <- ggplot(coor$cart_axes)+
    geom_text(aes(x=xlabel,y=ylabel,label = row.names(coor$cart_axes)),family = font,size = 6*sqrt(size)*size_axis_labels,hjust = "inward")+
    coord_fixed()+
    theme_minimal()+
    aes()+
    geom_point(aes(x=0,y=0),size=.5*size*size_center_dot)+
    geom_circle(data = coor$maingrid[coor$maingrid$alpha==.5,],aes(x0=x,y0=y,r=r),col = "gray90",linetype = "dotted",size=min(c(size,.75))*size_grid)+
    geom_circle(data = coor$maingrid[coor$maingrid$alpha==1,],aes(x0=x,y0=y,r=r),col = "gray20",linetype = "dotted",size=min(c(size,.75))*size_grid)+
    geom_segment(data = coor$cart_axes,aes(x=0,y=0,xend=x,yend=y),arrow = arrow(ends = "last",length = unit(.02*sqrt(size)*size_arrow_heads,"native"),type = "closed"),size=.5*sqrt(size)*width_axes)+
    geom_segment(data = coor$items[coor$items$width==max(coor$items$width),],aes(x=x1,y=y1,xend=x2,yend=y2),size=1,col = colour2)+
    geom_segment(data = coor$items[coor$items$width==min(coor$items$width),],aes(x=x1,y=y1,xend=x2,yend=y2),size=1,col = colour)+
    # width_items currently not supported since it shifts the edge of the bars away from the correct position determined by the center distance
    # geom_segment(data = coor$items,aes(x=x1,y=y1,xend=x2,yend=y2),size=size*width_items,col = colour)+
    geom_text(data = coor$factor_label,aes(x=x,y=y,label = label),family = font,size = 6*sqrt(size)*size_title,col=colour,fontface="bold")+
    theme(axis.line=element_blank(),axis.text.x=element_blank(),axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),axis.title.y=element_blank(),legend.position = "none",
          panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),plot.background=element_blank(),text = element_text(size = 16,family = font),plot.margin = margin(1,1,1,1,"in"))
  
  # adding tick label (optional)
  if(tick_label == TRUE && max(coor$maingrid$r)>=.5) myfbrv <- myfbrv +  geom_text(data = coor$axis_tick,aes(x,y,label = label),angle = (coor$axis_tick$phi-pi/48-pi/2)*180/pi,family = font,size = 3*sqrt(size)*size_tick_label,col = "gray20")
  
  # saving as .pdf file
  ggsave(paste(filename,".pdf",sep = ""),myfbrv,width = width ,height = height, units = "in",dpi = 3000)
  
  return(myfbrv)
}