#' Coord Items
#'
#' Generates coordinates for an item chart.
#'
#' @param data list generated by \code{\link{input_excel}}, or by hand,
#'   containing formatted data.
#' @param rotate_radians integer; radian angle to rotate the chart
#'   counter-clockwise by; use fractions of pi (e.g. pi/2 = 90 degrees).
#' @param rotate_degrees integer; angle in degrees to rotate the chart
#'   counter-clockwise by.
#'
#' @details Use this function in conjunction with \code{\link{plot_items}} for
#'   simple models.
#'
#'   Use \code{\link{item_chart}} to create the chart in a single step.
#'
#'   Rotate using this function, not \code{\link{plot_items}}.
#'
#'   In a nested model, it is more efficient to use \code{\link{coord_nested}}
#'   instead. Set \code{prepare_item_charts = TRUE} to generate item chart
#'   coordinates for all factors of the nested model.
#'
#' @return List containing coordinates of chart objects.
#'
#' @seealso \code{\link{plot_items}} \code{\link{coord_nested}} \code{\link{item_chart}}
#'
#' @examples
#' # # creating an item chart is a two step process, using this function and
#' # # plot_items:
#' # coord <- coord_items(DSSEI)
#' # DSSEI_items <- plot_items(coord, filename = "DSSEI_items")
#' # DSSEI_items
coord_items <- function (
  data,
  rotate_radians = 0,
  rotate_degrees = 0) {


  # helper variables -----------------------------------------------------------

  # number of facets (=subfactors)
  cplx <- length(colnames(data$cors))

  # total rotation value in radians
  rotate <- rotate_radians + rotate_degrees * pi / 180

  # maximum center distance (determining the chart size)
  maxcd <- max(data$cds$cd)


  # chart objects --------------------------------------------------------------

  ## axes ---------------------------

  # polar coordinates of axis line ends and axis labels
  # axis ends at 120 % of the maximum center distance
  # axis labels at 110 % of the axis ends
  p_axes <- data.frame(phi = rep(NA, cplx),
                       rho = NA,
                       rholabel = NA)
  row.names(p_axes) <- levels(data$cds$subfactor)
  p_axes$rho <- maxcd * 1.2
  p_axes$phi <- c(2 * pi / cplx * c(1:cplx)) + rotate
  p_axes$phi[p_axes$phi > 2 * pi] <-
    p_axes$phi[p_axes$phi > 2 * pi] - 2 * pi
  p_axes$rholabel <- p_axes$rho * 1.1

  # cartesian coordinates
  # x = cos(phi) * rho
  # y = sin(phi) * rho
  c_axes <- p_axes
  # rounded values to decrease display length in console
  c_axes[ ,1] <- round(cos(p_axes$phi) * p_axes$rho, digits = 7)
  c_axes[ ,2] <- round(sin(p_axes$phi) * p_axes$rho, digits = 7)
  c_axes[ ,3] <- round(cos(p_axes$phi) * p_axes$rholabel, digits = 7)
  c_axes[ ,4] <- round(sin(p_axes$phi) * p_axes$rholabel, digits = 7)
  names(c_axes) <- c("x", "y", "xlabel", "ylabel")

  # axis tick label
  # reflecting the default settings of other charts,
  # the axis tick of 0.1 is labeled
  # the axis tick label automatically shows within the first quadrant
  axis_tick <- data.frame(
    rho = 0.14,
    label = "0.1",
    phi = NA,
    x = NA,
    y = NA)
  axis_tick$phi <- min(p_axes$phi[p_axes$rho>.1]) +
    pi / 32 / axis_tick$rho
  axis_tick$x <- round(cos(axis_tick$phi) * axis_tick$rho, digits = 7)
  axis_tick$y <- round(sin(axis_tick$phi) * axis_tick$rho, digits = 7)


  ## items --------------------------

  # coordinates of item bars
  # the length of item bars alternates between long and short to better
  # distinguish similar items
  # the length of item bars is relative to the overall size of the chart
  # center distances = from the origin to the inner edge of the item bar
  # n = number of items
  n <- length(data$cds$item)
  items <- data.frame(
    rho = rep(NA, n), phi = NA,
    x   = NA, y   = NA,
    x1  = NA, y1  = NA,
    x2  = NA, y2  = NA,
    length = NA)
  row.names(items) <- data$cds$item
  items$phi <- p_axes$phi[data$cds$subfactor]
  items$rho <- data$cds$cd + .01
  items <- items[order(items$phi, items$rho), ]
  items$x <- round(cos(items$phi) * items$rho, digits = 7)
  items$y <- round(sin(items$phi) * items$rho, digits = 7)
  items$length <- 0.85 * maxcd
  items$length[seq(from = 1, by = 2, to = length(items$length))] <- 1.15 * maxcd
  items$x1 <- items$x-items$y / items$rho * .03 * items$length
  items$y1 <- items$y + items$x / items$rho * .03 * items$length
  items$x2 <- items$x + items$y / items$rho * .03 * items$length
  items$y2 <- items$y-items$x / items$rho * .03 * items$length


  ## grid ---------------------------

  # coordinates of grid
  # grid density is one line every 0.1 center distance
  # the grid ends right before the maximum center distance
  # grid lines are accentuated at 0.1 and multiples of 0.5
  # n = number of grid lines
  n <- trunc(maxcd * 10)
  maingrid <- data.frame(x = rep(0, n),
                         y = 0,
                         r = NA,
                         alpha = NA)
  maingrid$r <- seq(from = .1, by = .1, to = round(maxcd, digits = 2))
  maingrid$alpha <- .5
  if (n > 4) maingrid$alpha[seq(from = 5, by = 5, to = n)] <- 1
  maingrid$alpha[1] <- 1


  ## title --------------------------

  # coordinates of factor name
  # the factor label automatically shows between the first two facets
  # the factor label shows at half the maximum center distance from the origin
  title <- data.frame(phi = mean(p_axes$phi[1] + pi / cplx),
                      rho = .5 * maxcd,
                      label = data$cds$factor[1],
                      x = NA, y = NA)
  title$x <- round(cos(title$phi) * title$rho, digits = 7)
  title$y <- round(sin(title$phi) * title$rho, digits = 7)


  # return ---------------------------------------------------------------------

  # list of all dataframes containing the coordinates of the chart objects
  coord <- list(p_axes    = p_axes,
                c_axes    = c_axes,
                items     = items,
                maingrid  = maingrid,
                axis_tick = axis_tick,
                title     = title)

  return(coord)
}
