#' Coord Facets
#'
#' Generates coordinates for a facet chart.
#'
#' @param data list generated by \code{\link{input_excel}}, or by hand,
#'   containing formatted data.
#' @param subradius integer; radius of the circles representing facets (same
#'   unit as center distances).
#' @param rotate_radians integer; radian angle to rotate the chart
#'   counter-clockwise by; use fractions of pi (e.g. pi/2 = 90 degrees).
#' @param rotate_degrees integer; angle in degrees to rotate the chart
#'   counter-clockwise by.
#'
#' @details Use this function in conjunction with \code{\link{plot_facets}} for
#'   simple models.
#'
#'   In a nested model, it is more efficient to use \code{\link{coord_nested}}
#'   instead. It automatically generates coordinates for all factors of the
#'   nested model.
#'
#' @return List containing coordinates of chart objects.
#'
#' @seealso \code{\link{plot_facets}}
#'
#' @examples
#' # creating a facet chart is a two step process, using this function and plot_facets:
#' coord <- coord_facets(DSSEI, subradius = .5)
#' DSSEI_facets <- plot_facets(coord, filename = "DSSEI_facets")
#' DSSEI_facets
#'
#' @export
coord_facets <- function (data, subradius, rotate_radians = 0, rotate_degrees = 0) {


# helper variables ------------------------------------------------------------

  # number of facets (=subfactors)
  cplx <- data$parameters$complexity

  # total rotation value in radians from rotation parameters
  rotate <- rotate_radians + rotate_degrees * pi / 180


# chart objects ---------------------------------------------------------------

    ## circles ------------------------

  # polar coordinates of circles
    # the main circle is the first in the data frame and centered on the origin (0,0)
    # the main circle's radius is set so it encloses the furthest circle
  pol_circles <- data.frame(phi = rep(NA, cplx + 1),
                            rho = rep(NA, cplx + 1),
                            radius = rep(NA, cplx + 1))
  row.names(pol_circles) <- c(levels(data$center_distances$factor),
                              levels(data$center_distances$subfactor))
  pol_circles$radius[1] <- max(data$center_distances$mean_center_distance) +
                           2 * subradius
  pol_circles$radius[2:length(pol_circles$radius)] <- subradius
  pol_circles$rho <- c(0, tapply(data$center_distances$center_distance,
                                 data$center_distances$subfactor,
                                 mean) + subradius)
    # facet circles are spread evenly in a circle
  pol_circles$phi <- c(0, 2 * pi / cplx * c(1:cplx)) + rotate

  # cartesian coordinates
    # x = cos(phi) * rho
    # y = sin(phi) * rho
  cart_circles <- pol_circles
    # rounded values to decrease display length in console
  cart_circles[ ,1] <- round(cos(pol_circles$phi) * pol_circles$rho, digits = 7)
  cart_circles[ ,2] <- round(sin(pol_circles$phi) * pol_circles$rho, digits = 7)
  names(cart_circles) <- c("x","y","radius")
  row.names(cart_circles)[1] <- ""


    ## axes ---------------------------

  # polar coordinates of radial axes
    # axes are split into two segments by the facet circles:
    # one from the origin (rho0) to the inner edge of the facet circles (rho1), the center distance
    # one from the outer edge of the facet circles (rho2) to the edge of the main circle (rho3)
  pol_axes <- data.frame(rho0 = rep(0, cplx),
                         rho1 = rep(NA, cplx),
                         rho2 = rep(NA, cplx),
                         rho3 = rep(NA,cplx),
                         phi = rep(NA,cplx))
  row.names(pol_axes) <- c(levels(data$center_distances$subfactor))
  pol_axes$phi <- utils::tail(pol_circles$phi, cplx)
  pol_axes$rho1 <- utils::tail(pol_circles$rho, cplx) - subradius
  pol_axes$rho2 <- pol_axes$rho1 + 2 * subradius
  pol_axes$rho3 <- rep(max(pol_circles$radius))

  # cartesian coordinates
  cart_axes <- data.frame(x0 = rep(NA, cplx), y0 = rep(NA, cplx),
                          x1 = rep(NA, cplx), y1 = rep(NA, cplx),
                          x2 = rep(NA, cplx), y2 = rep(NA, cplx),
                          x3 = rep(NA, cplx), y3 = rep(NA, cplx))
  row.names(cart_axes) <- c(levels(data$center_distances$subfactor))
  cart_axes$x0 <- round(cos(pol_axes$phi) * pol_axes$rho0, digits = 7)
  cart_axes$x1 <- round(cos(pol_axes$phi) * pol_axes$rho1, digits = 7)
  cart_axes$x2 <- round(cos(pol_axes$phi) * pol_axes$rho2, digits = 7)
  cart_axes$x3 <- round(cos(pol_axes$phi) * pol_axes$rho3, digits = 7)
  cart_axes$y0 <- round(sin(pol_axes$phi) * pol_axes$rho0, digits = 7)
  cart_axes$y1 <- round(sin(pol_axes$phi) * pol_axes$rho1, digits = 7)
  cart_axes$y2 <- round(sin(pol_axes$phi) * pol_axes$rho2, digits = 7)
  cart_axes$y3 <- round(sin(pol_axes$phi) * pol_axes$rho3, digits = 7)

  # coordinates of axis tick label
    # this is only a template and sets the axis tick to 1
    # the actual tick is defined in the plot function by
    # multiplying x and y with the tick value (defaults to 0.1)
    # the axis tick label is displayed between the rightmost axis and the next one counter-clockwise
  axis_tick <- data.frame(rho = 1, phi = NA, x = NA, y = NA)
  axis_tick$phi <- min(pol_axes$phi) - pi / cplx
  axis_tick$x <- round(cos(axis_tick$phi) * axis_tick$rho, digits = 7)
  axis_tick$y <- round(sin(axis_tick$phi) * axis_tick$rho, digits = 7)


    ## title --------------------------

  # coordinates of the title
    # the factor label automatically shows next to the lowest mean center distance (clockwise)
    # the factor label shows at 2/3 of the distance from the origin to the edge of the main circle
  factor_label <- data.frame(x = NA,
                             y = NA,
                             label = row.names(pol_circles)[1],
                             phi = NA,
                             rho = NA)
  factor_label$phi <- pol_circles[which.min(pol_circles$rho), "phi"] - pi / cplx
  factor_label$rho <- 2 / 3 * max(pol_circles$radius)
  factor_label$x <- round(cos(factor_label$phi) * factor_label$rho, digits = 7)
  factor_label$y <- round(sin(factor_label$phi) * factor_label$rho, digits = 7)


    ## correlations -------------------

  # coordinates of latent facet correlation labels
    # each correlation label appears twice: once in each facet's circle
    # n = 2 * number of correlations
  n <- cplx * (cplx - 1)
  inner_cors <- data.frame(x = rep(NA, n),
                           y = rep(NA, n),
                           V1 = rep(NA, n),
                           V2 = rep(NA, n),
                           label = rep(NA, n),
                           xnew = rep(NA, n),
                           ynew = rep(NA,n))

  # all pairs of subfactors are covered twice, once in every order, excluding self-pairing
  a <- row.names(data$subfactor_cors)
  a <- c(a, a[1])
  b <- NULL
  for (k in 1:cplx) {
    b <- c(b, a[-c(1, cplx + 1)])
    a <- a[-1]
    a <- c(a, a[1])
  }
  inner_cors$V1 <- b
  inner_cors$V2 <- unlist(lapply(row.names(data$subfactor_cors), FUN = rep, times = cplx - 1))

  # correlation values
  for (k in 1:n) {
    inner_cors$label[k] <- data$subfactor_cors[inner_cors$V1[k], inner_cors$V2[k]]
  }
  inner_cors$label <- as.character(inner_cors$label)
  # exclude leading 0's for aesthetic reasons
  inner_cors$label[inner_cors$label < 1] <- substr(inner_cors$label, 2, 4)


  # label coordinates
  inner_cors$x <- cart_circles[inner_cors$V2, "x"]
  inner_cors$y <- cart_circles[inner_cors$V2, "y"]

  # scattered as list in the general direction of the partner variable
  scatter <- rep(seq(from = (-pi + 2 * pi / cplx) / 2,
                     to = (pi - 2 * pi / cplx) / 2,
                     by = (pi - 2 * pi / cplx) / (cplx - 2)),
                 cplx)
  rho <- pol_circles[inner_cors$V2, "radius"] * .75
  phi <- pol_circles[inner_cors$V2, "phi"]
  inner_cors$xnew <- inner_cors$x + round(cos(phi + pi + scatter), digits = 7) * rho
  inner_cors$ynew <- inner_cors$y + round(sin(phi + pi + scatter), digits = 7) * rho
  inner_cors$x <- inner_cors$xnew
  inner_cors$y <- inner_cors$ynew
  inner_cors[6:7] <- list(NULL)


# return ----------------------------------------------------------------------

  # list of all dataframes containing the coordinates of the chart objects
  coord <- list(pol_circles = pol_circles,
               cart_circles = cart_circles,
               pol_axes = pol_axes,
               cart_axes = cart_axes,
               axis_tick = axis_tick,
               factor_label = factor_label,
               inner_cors = inner_cors)

  return(coord)
}
