#' Coord Facets
#'
#' Generates coordinates for a facet chart.
#'
#' @param data list generated by \code{\link{input_excel}}, or by hand,
#'   containing formatted data.
#' @param subradius integer; same unit as center distances; radius of the
#'   circles representing facets; use to avoid circle overlap and optimize
#'   appearance; if 0 (default) a value is chosen automatically.
#' @param tick numeric; axis tick position; if 0 (default) a value is chosen
#'   automatically.
#' @param rotate_radians integer; radian angle to rotate the chart
#'   counter-clockwise by; use fractions of pi (e.g. pi/2 = 90 degrees).
#' @param rotate_degrees integer; angle in degrees to rotate the chart
#'   counter-clockwise by.
#' @param rotate_title_radians integer; radian angle to rotate the global label
#'   counter-clockwise by; use fractions of pi (e.g. pi/2 = 90 degrees).
#' @param rotate_title_degrees integer; angle in degrees to rotate the global
#'   label counter-clockwise by.
#'
#' @details Use this function in conjunction with \code{\link{plot_facets}} for
#'   simple models.
#'
#'   Use \code{\link{facet_chart}} to create the chart in a single step.
#'
#'   Rotate or change the size of the circles using this function, not
#'   \code{\link{plot_facets}}.
#'
#'   In a nested model, it is more efficient to use \code{\link{coord_nested}}
#'   instead. It automatically generates coordinates for all factors of the
#'   nested model.
#'
#' @return List containing coordinates of chart objects.
#'
#' @seealso \code{\link{plot_facets}} \code{\link{facet_chart}}
#'
#' @examples
#' # # creating a facet chart is a two step process, using this function and
#' # # plot_facets:
#' # coord <- coord_facets(DSSEI, subradius = .5)
#' # DSSEI_facets <- plot_facets(coord, filename = "DSSEI_facets")
#' # DSSEI_facets
coord_facets <- function (
  data,
  subradius = 0,
  tick = 0,
  rotate_radians = 0,
  rotate_degrees = 0,
  rotate_title_radians = 0,
  rotate_title_degrees = 0) {


  # helper variables -----------------------------------------------------------

  # number of facets (=subfactors)
  cplx <- length(colnames(data$cors))

  # total rotation value in radians from rotation parameters
  rotate <- rotate_radians + rotate_degrees * pi / 180

  # total title rotation value in radians
  rotate_title <- rotate_title_radians + rotate_title_degrees * pi / 180

  # mean center distances
  mcd <- data$cds$mean_cd

  # default axis tick
  if (tick == 0){
    tick <- signif(max(.15 * max(mcd), .3 * min(mcd)), 1)
    sc <- rep(c(1, 2, 5), 5) * 10 ^ rep(-3:1, each = 3)
    tick <- sc[which.min(abs(tick - sc))]
  }

  # default subradius
  if (subradius == 0) {
    subradius <- max(mean(mcd), .25 * max(mcd)) *
    (5 / (3 + cplx)) *
    (.25 + .25 * (min(max(mean(mcd), .25 * max(mcd)) / stats::sd(mcd), 3)))
  }

  # chart objects --------------------------------------------------------------

  ## circles ------------------------

  # polar coordinates of circles
  # the main circle is the first in the data frame and centered
  # on the origin (0,0)
  # the main circle's radius is set so it encloses the furthest circle
  p_circs <- data.frame(phi = rep(NA, cplx + 1),
                        rho = 0,
                        radius = NA)
  row.names(p_circs) <- c(levels(data$cds$factor),
                          colnames(data$cors))
  p_circs$radius[1] <- max(mcd) + 2 * subradius
  p_circs$radius[2:length(p_circs$radius)] <- subradius
  mean_cds <- tapply(data$cds$cd, data$cds$subfactor, mean)
  p_circs[colnames(data$cors), "rho"] <- c(mean_cds[colnames(data$cors)] + subradius)
  rm(mean_cds)
  # facet circles are spread evenly in a circle
  p_circs$phi <- c(0, 2 * pi / cplx * c(1:cplx)) + rotate
  p_circs$phi[p_circs$phi > 2 * pi] <-
    p_circs$phi[p_circs$phi > 2 * pi] - 2 * pi

  # cartesian coordinates
  # x = cos(phi) * rho
  # y = sin(phi) * rho
  c_circs <- p_circs
  # rounded values to decrease display length in console
  c_circs[ ,1] <- round(cos(p_circs$phi) * p_circs$rho, digits = 7)
  c_circs[ ,2] <- round(sin(p_circs$phi) * p_circs$rho, digits = 7)
  names(c_circs) <- c("x","y","radius")
  row.names(c_circs)[1] <- ""


  ## axes ---------------------------

  # polar coordinates of radial axes
  # axes are split into two segments by the facet circles:
  # one from the origin (rho0) to the inner edge of the facet circles (rho1),
  # the center distance
  # one from the outer edge of the facet circles (rho2) to the edge of
  # the main circle (rho3)
  p_axes <- data.frame(rho0 = rep(0, cplx),
                       rho1 = NA,
                       rho2 = NA,
                       rho3 = NA,
                       phi = NA)
  row.names(p_axes) <- c(colnames(data$cors))
  p_axes$phi <- utils::tail(p_circs$phi, cplx)
  p_axes$rho1 <- utils::tail(p_circs$rho, cplx) - subradius
  p_axes$rho2 <- p_axes$rho1 + 2 * subradius
  p_axes$rho3 <- rep(max(p_circs$radius))

  # cartesian coordinates
  c_axes <- data.frame(x0 = rep(NA, cplx), y0 = NA,
                       x1 = NA, y1 = NA,
                       x2 = NA, y2 = NA,
                       x3 = NA, y3 = NA)
  row.names(c_axes) <- c(colnames(data$cors))
  c_axes$x0 <- round(cos(p_axes$phi) * p_axes$rho0, digits = 7)
  c_axes$x1 <- round(cos(p_axes$phi) * p_axes$rho1, digits = 7)
  c_axes$x2 <- round(cos(p_axes$phi) * p_axes$rho2, digits = 7)
  c_axes$x3 <- round(cos(p_axes$phi) * p_axes$rho3, digits = 7)
  c_axes$y0 <- round(sin(p_axes$phi) * p_axes$rho0, digits = 7)
  c_axes$y1 <- round(sin(p_axes$phi) * p_axes$rho1, digits = 7)
  c_axes$y2 <- round(sin(p_axes$phi) * p_axes$rho2, digits = 7)
  c_axes$y3 <- round(sin(p_axes$phi) * p_axes$rho3, digits = 7)

  # coordinates of axis tick label
  # sets the tick to a rounded half minimum mean center distance and can be
  # overwritten manually
  # the axis tick label is displayed between the rightmost axis and the next one
  # counter-clockwise
  axis_tick <- data.frame(rho = tick, phi = NA, x = NA, y = NA)
  axis_tick$phi <- min(p_circs$phi) + pi / cplx
  axis_tick$x <- round(cos(axis_tick$phi) * axis_tick$rho, digits = 7)
  axis_tick$y <- round(sin(axis_tick$phi) * axis_tick$rho, digits = 7)


  ## title --------------------------

  # coordinates of the title
  # the factor label automatically shows next to the lowest mean center distance
  # (clockwise)
  # the factor label shows at 2/3 of the distance from the origin to the edge of
  # the main circle
  title <- data.frame(x = NA,
                      y = NA,
                      label = row.names(p_circs)[1],
                      phi = NA,
                      rho = NA)
  title$phi <- p_circs[which.min(p_circs$rho), "phi"] - pi / cplx + rotate_title
  title$rho <- 2 / 3 * max(p_circs$radius)
  title$x <- round(cos(title$phi) * title$rho, digits = 7)
  title$y <- round(sin(title$phi) * title$rho, digits = 7)


  ## correlations -------------------

  # coordinates of latent facet correlation labels
  # each correlation label appears twice: once in each facet's circle
  # n = 2 * number of correlations
  n <- cplx * (cplx - 1)
  cors <- data.frame(x = rep(NA, n),
                     y = NA,
                     V1 = NA,
                     V2 = NA,
                     label = NA,
                     xnew = NA,
                     ynew = NA)

  # all pairs of subfactors are covered twice, once in every order,
  # excluding self-pairing
  a <- row.names(data$cors)
  a <- c(a, a[1])
  b <- NULL
  for (k in 1:cplx) {
    b <- c(b, a[-c(1, cplx + 1)])
    a <- a[-1]
    a <- c(a, a[1])
  }
  cors$V1 <- b
  cors$V2 <- unlist(lapply(row.names(data$cors), FUN = rep, times = cplx - 1))

  # correlation values
  for (k in 1:n) {
    cors$label[k] <- data$cors[cors$V1[k], cors$V2[k]]
  }
  cors$label <- as.character(cors$label)
  # exclude leading 0's for aesthetic reasons
  cors$label[cors$label != 1 && cors$label != 0] <- substr(cors$label, 2, 4)


  # label coordinates
  cors$x <- c_circs[cors$V2, "x"]
  cors$y <- c_circs[cors$V2, "y"]

  # scattered as list in the general direction of the partner variable
  scatter <- rep(seq(from = (-pi + 2 * pi / cplx) / 2,
                     to   = (pi  - 2 * pi / cplx) / 2,
                     by   = (pi  - 2 * pi / cplx) / (cplx - 2)),
                 cplx)
  rho <- p_circs[cors$V2, "radius"] * .75
  phi <- p_circs[cors$V2, "phi"]
  cors$xnew <- cors$x + round(cos(phi + pi + scatter), digits = 7) * rho
  cors$ynew <- cors$y + round(sin(phi + pi + scatter), digits = 7) * rho
  cors$x <- cors$xnew
  cors$y <- cors$ynew
  cors[6:7] <- list(NULL)


  # return ---------------------------------------------------------------------

  # list of all dataframes containing the coordinates of the chart objects
  coord <- list(p_circs   = p_circs,
                c_circs   = c_circs,
                p_axes    = p_axes,
                c_axes    = c_axes,
                axis_tick = axis_tick,
                title     = title,
                cors      = cors)

  return(coord)
}
