#' Default Subradius
#'
#' Calculates a subradius for facet charts that fits the data.
#'
#' @param data list generated by \code{\link{input_excel}}, or by hand,
#'   containing formatted data.
#'
#' @return integer, default subradius
def_subradius <- function (data) {
  cplx <- length(colnames(data$cors))
  mcd <- data$cds$mean_cd
  subradius <- max(mean(mcd), .25 * max(mcd)) *
    (5 / (3 + cplx)) *
    (.25 + .25 * (min(max(mean(mcd), .25 * max(mcd)) / stats::sd(mcd), 3)))
}
