#' Facet Chart
#'
#' Creates a facet chart, showing the facets of a test.
#'
#' @param data list generated by \code{\link{input_excel}}, or by hand,
#'   containing formatted data.
#' @param subradius integer; same unit as center distances; radius of the
#'   circles representing facets; use to avoid circle overlap and optimize
#'   appearance; if 0 (default) a value is chosen automatically.
#' @param filename character; name of the file to save. Supported formats are:
#'   "pdf" (best quality with lowest file size), "png", "jpeg". Use "none" to
#'   suppress file output; defaults to "myipv.pdf".
#' @param size integer; smartly scaled size of chart objects.
#' @param font character; text font; defaults to 'sans' (use extrafonts to
#'   install additional fonts).
#' @param rotate_radians integer; radian angle to rotate the chart
#'   counter-clockwise by; use fractions of pi (e.g. pi/2 = 90 degrees).
#' @param rotate_degrees integer; angle in degrees to rotate the chart
#'   counter-clockwise by.
#' @param filewidth integer; width of the graphic in inches; defaults to 10.
#' @param fileheight integer; height of the graphic in inches; defaults to 10.
#' @param dpi integer; resolution in dots per inch; defaults to 500.
#' @param color character; name of the accent color.
#' @param fade integer; brightness of the gray tones between 0 (black) and 100
#'   (white) in steps of 1; defaults to 85.
#' @param tick numeric; axis tick position; if 0 (default) a value is chosen
#'   automatically.
#' @param cor_labels logical; if \code{TRUE}, draws latent correlations between
#'   facets as text.
#' @param rotate_title_radians integer; radian angle to rotate the global label
#'   counter-clockwise by; use fractions of pi (e.g. pi/2 = 90 degrees).
#' @param rotate_title_degrees integer; angle in degrees to rotate the global
#'   label counter-clockwise by.
#' @param size_test_label integer; font size of the test label (relative to
#'   default).
#' @param size_facet_labels integer; font size of the facet labels (relative to
#'   default).
#' @param width_axes integer; width of the radial axis lines indicating center
#'   distances (relative to default).
#' @param width_circles integer; width of the circle outlines (relative to
#'   default).
#' @param width_tick integer; width of the dotted axis tick line (relative to
#'   default).
#' @param size_tick_label integer; font size of the axis tick label (relative to
#'   default).
#' @param size_cor_labels integer; font size of the latent correlations between
#'   facets (relative to default).
#'
#' @return Object of the class "ggplot" and optionally the same object saved as
#'   a file.
#'
#' @seealso \code{\link{item_chart}} \code{\link{nested_chart}}
#'
#' @examples
#' # as simple as that
#' facet_chart(SMTQ, subradius = .6)
#'
#' @export
facet_chart <- function(
  data,
  subradius = 0,
  filename = "myipv.pdf",
  size = 1,
  font = "sans",
  rotate_radians = 0,
  rotate_degrees = 0,
  filewidth = 10,
  fileheight = 10,
  dpi = 500,
  color = "black",
  fade = 85,
  tick = 0,
  cor_labels = TRUE,
  rotate_title_radians = 0,
  rotate_title_degrees = 0,
  size_cor_labels = 1,
  size_test_label = 1,
  size_facet_labels = 1,
  width_axes = 1,
  width_circles = 1,
  width_tick = 1,
  size_tick_label = 1){

  coord <- coord_facets(
    data = data,
    subradius = subradius,
    tick = tick,
    rotate_radians = rotate_radians,
    rotate_degrees = rotate_degrees,
    rotate_title_radians =rotate_title_radians,
    rotate_title_degrees = rotate_title_degrees)

  myipv <- plot_facets(
    coord = coord,
    size = size,
    filename = filename,
    filewidth = filewidth,
    fileheight = fileheight,
    dpi = dpi,
    color = color,
    fade = fade,
    font = font,
    cor_labels = cor_labels,
    size_cor_labels = size_cor_labels,
    size_test_label = size_test_label,
    size_facet_labels = size_facet_labels,
    width_axes = width_axes,
    width_circles = width_circles,
    width_tick = width_tick,
    size_tick_label = size_tick_label)

  return(myipv)
}
