#' Facet Chart
#'
#' Creates a facet chart, showing the facets of a test.
#'
#' @param data list generated by \code{\link{input_excel}}, or by hand,
#'   containing formatted data.
#' @param subradius integer; (arbitrary) radius of the circles representing
#'   facets (same unit as center distances), use to avoid circle overlap and
#'   optimize appearance.
#' @param rotate_radians integer; radian angle to rotate the chart
#'   counter-clockwise by; use fractions of pi (e.g. pi/2 = 90 degrees).
#' @param rotate_degrees integer; angle in degrees to rotate the chart
#'   counter-clockwise by.
#' @param size integer; smartly scaled size of chart objects.
#' @param file character; file format to save. Supported formats are: "pdf"
#'   (best quality with lowest file size),"png","jpeg". Suppress file output
#'   using any other value; defaults to "pdf".
#' @param filename character string; name of the file the chart is written to;
#'   filename extension added from file parameter like this: [filename].[file].
#' @param filewidth integer; width of the .pdf file; defaults to 10, dpi is
#'   3000.
#' @param fileheight integer; height of the .pdf file; defaults to 10, dpi is
#'   3000.
#' @param colour character; name of the accent colour.
#' @param fade integer; brightness of the gray tones between 0 (black) and 100
#'   (white) in steps of 1; defaults to 90.
#' @param cor_labels logical; if \code{TRUE}, draws latent correlations between
#'   facets as text.
#' @param tick numeric; axis tick position; defaults to .1.
#' @param font character; text font; defaults to 'sans' (use extrafonts to
#'   install additional fonts).
#' @param size_test_label integer; font size of the test label (relative to
#'   default).
#' @param size_facet_labels integer; font size of the facet labels (relative to
#'   default).
#' @param width_axes integer; width of the radial axis lines indicating center
#'   distances (relative to default).
#' @param width_circles integer; width of the circle outlines (relative to
#'   default).
#' @param width_tick integer; width of the dotted axis tick line (relative to
#'   default).
#' @param size_tick_label integer; font size of the axis tick label (relative to
#'   default).
#' @param size_cor_labels integer; font size of the latent correlations between
#'   facets (relative to default).
#' @param size_center_dot integer; size of the center dot marking the origin
#'   (relative to default).
#'
#' @details This function creates the chart in one step, but does not return the
#'   coordinates from \code{\link{coord_facets}}. Alternatively use
#'   \code{\link{coord_facets}} and \code{\link{plot_facets}}. This allows you to
#'   make changes to or reuse the coordinates.
#'
#' @return Object of the class "ggplot" and optionally the same object saved as
#'   a file.
#'
#' @seealso \code{\link{coord_facets}} \code{\link{plot_facets}}
#'
#' @examples
#' # as simple as that
#' facet_chart(SMTQ, subradius = .6)
#'
#' @export
facet_chart <- function(
  data,
  subradius,
  rotate_radians = 0,
  rotate_degrees = 0,
  size = 1,
  file = "pdf",
  filename = NULL,
  filewidth = 10,
  fileheight = 10,
  colour = "black",
  fade = 90,
  font = "sans",
  tick = .1,
  cor_labels = TRUE,
  size_cor_labels = 1,
  size_test_label = 1,
  size_facet_labels = 1,
  width_axes = 1,
  width_circles = 1,
  width_tick = 1,
  size_tick_label = 1,
  size_center_dot = 1){

  coord <- coord_facets(
    data = data,
    subradius = subradius,
    rotate_radians = rotate_radians,
    rotate_degrees = rotate_degrees)

  myipv <- plot_facets(
    coord = coord,
    size = size,
    file = file,
    filename = filename,
    filewidth = filewidth,
    fileheight = fileheight,
    colour = colour,
    fade = fade,
    font = font,
    tick = tick,
    cor_labels = cor_labels,
    size_cor_labels = size_cor_labels,
    size_test_label = size_test_label,
    size_facet_labels = size_facet_labels,
    width_axes = width_axes,
    width_circles = width_circles,
    width_tick = width_tick,
    size_tick_label = size_tick_label,
    size_center_dot = size_center_dot)

  return(myipv)
}
