#' Input Manual Process
#'
#' Preprocesses the data generated by \code{\link{input_manual_simple}} or
#' \code{\link{input_manual_nested}}.
#'
#' @param data list generated by \code{\link{input_manual_simple}} or
#' \code{\link{input_manual_nested}} with complete data.
#'
#' @return List containing formatted data including center distances for
#'   \code{\link{item_chart}}, \code{\link{facet_chart}}, and
#'   \code{\link{nested_chart}}.
#'
#'   @seealso \code{\link{input_manual_simple}} \code{\link{input_manual_nested}}
#'
#'@examples
#'# these RSES data can also be seen in self_confidence, the example data of
#'# this package
#'mydata <- input_manual_simple(
#'test_name = "RSES",
#'facet_names = c("Ns", "Ps"),
#'items_per_facet = 5,
#'item_names = c(2, 5, 6, 8, 9,
#'               1, 3, 4, 7, 10),
#'general_loadings = c(.5806, .5907, .6179, .5899, .6559,
#'                     .6005, .4932, .4476, .5033, .6431),
#'correlated_loadings = c(.6484, .6011, .6988, .6426, .6914,
#'                        .6422, .5835, .536, .5836, .6791),
#'correlation_matrix = matrix(data = c(1, .69,
#'                                     .69, 1),
#'                            nrow = 2,
#'                            ncol = 2))
#'mydata
#'input_manual_process(mydata)
#'
#' @export
input_manual_process <- function(data) {

  if (names(data)[1] == "global") { # nested case
    mydata$global <- input_manual_process_factor(data$global)
    mydata$tests <- lapply(data$tests, input_manual_process_factor)

  } else { # simple case
    mydata <- input_manual_process_factor(data)
  }


  # return ---------------------------------------------------------------------

  return(mydata)
}






#' Input Manual Process Factor
#'
#' Helper function of \code{\link{input_manual_process}}.
#'
#' @param data list generated by \code{\link{input_manual_simple}} with complete
#'   data.
#'
#' @return List containing formatted data including center distances for a
#'   single factor.
input_manual_process_factor <- function(data) {

  # checking and recalculating -------------------------------------------------

  ## factor loadings ---------------------------------------

  # checking for factor loadings below .1
  bad <- min(c(data$fls$factor_loading, data$fls$subfactor_loading))
  bad <- bad < 0.1
  if (bad) warning ("At least one factor loading set to minimum of 0.1")
  data$fls$factor_loading[data$fls$factor_loading < .1] <- .1
  data$fls$subfactor_loading[data$fls$subfactor_loading < .1] <- .1


  ## center distances --------------------------------------

  # calculating the center distances
  cds <- data.frame(
    factor = data$fls$factor,
    subfactor = data$fls$subfactor,
    item = as.factor(data$fls$item),
    cd = data$fls$subfactor_loading ^ 2 / data$fls$factor_loading ^ 2 - 1,
    mean_cd = NA)

  # checking for negative center distances
  bad <- min(cds$cd)
  bad <- bad < 0
  if (bad) warning ("At least one negative center distance adjusted to 0")
  cds$cd[cds$cd < 0] <- 0

  # calculating mean center distances of facets
  mean_cds <- lapply(split(cds, cds$subfactor),
                     function (x) x$mean_cd <- mean(x$cd))
  cds$mean_cd <- as.numeric(mean_cds[cds$subfactor])


  # return ---------------------------------------------------------------------

  mydata <- list(cds = cds,
                 cors = data$cors,
                 pars = data$pars)

  return(mydata)

}
