#' Item Chart
#'
#' Creates an item chart, showing the items of a test arranged by facets.
#'
#' @param data list generated by \code{\link{input_excel}}, or by hand,
#'   containing formatted data.
#' @param filename character; name of the file to save. Supported formats are:
#'   "pdf" (best quality with lowest file size), "png", "jpeg". Use "none" to
#'   suppress file output; defaults to "myipv.pdf".
#' @param size integer; smartly scaled size of chart objects except item bars.
#' @param font character; text font; defaults to 'sans' (use extrafonts to
#'   install additional fonts).
#' @param rotate_radians integer; radian angle to rotate the chart
#'   counter-clockwise by; use fractions of pi (e.g. pi/2 = 90 degrees).
#' @param rotate_degrees integer; angle in degrees to rotate the chart
#'   counter-clockwise by.
#' @param filewidth integer; width of the graphic in inches; defaults to 12.
#' @param fileheight integer; height of the graphic in inches; defaults to 10.
#' @param dpi integer; resolution in dots per inch; defaults to 500.
#' @param colour character; name of the first accent colour; defaults to black.
#' @param colour2 character; name of the second accent colour; defaults to black.
#' @param fade integer; brightness of minor grid lines, gray tones between 0
#'   ("white") and 100 ("black") in steps of 1; defaults to 15.
#' @param dodge_axes integer; relative amount of horizontal outward dodge of
#'   axis labels.
#' @param tick_label logical; if \code{TRUE}, draws a text label for the axis
#'   tick.
#' @param rotate_title_radians integer; radian angle to rotate the global label
#'   counter-clockwise by; use fractions of pi (e.g. pi/2 = 90 degrees).
#' @param rotate_title_degrees integer; angle in degrees to rotate the global
#'   label counter-clockwise by.
#' @param width_items integer; width of the item bars (relative to default).
#' @param length_items integer; length of the item bars (relative to default).
#' @param length_ratio_items integer; relative length of every other item bar;
#'   defaults to 1.5.
#' @param size_title integer; font size of the test label (relative to default).
#' @param size_facet_labels integer; font size of the axis labels (relative to
#'   default).
#' @param width_axes integer; width of the radial axis lines indicating center
#'   distances (relative to default).
#' @param size_arrow_heads integer; length of the arrow heads at the end of the
#'   axes (relative to default).
#' @param width_grid integer; width of the dotted grid lines (relative to
#'   default).
#' @param size_tick_label integer; font size of the axis tick label (relative to
#'   default).
#' @param size_center_dot integer; size of the center dot marking the origin
#'   (relative to default).
#'
#' @return Object of the class "ggplot" and optionally the same object saved as
#'   a file.
#'
#' @details When changing the size of objects, consider the \code{size}
#'   parameter first and make specific adjustments with the other \code{size_}
#'   and \code{width_} parameters after.
#'
#'   To better display overlapping item values, change the width of the item
#'   bars, or set the accent colours to different values, or change the ratio of
#'   item lengths.
#'
#' @seealso \code{\link{facet_chart}} \code{\link{nested_chart}}
#'
#' @examples
#' # as simple as that
#' item_chart(SMTQ)
#'
#' @export
item_chart <- function(
  data,
  filename = "myipv.pdf",
  size = 1,
  font = "sans",
  rotate_radians = 0,
  rotate_degrees = 0,
  filewidth = 12,
  fileheight = 10,
  dpi = 500,
  colour = "black",
  colour2 = "black",
  fade = 15,
  dodge_axes = 1,
  tick_label = TRUE,
  rotate_title_radians = 0,
  rotate_title_degrees = 0,
  width_items = 1,
  length_items = 1,
  length_ratio_items = 1.5,
  size_tick_label = 1,
  size_title = 1,
  size_facet_labels = 1,
  width_axes = 1,
  size_arrow_heads = 1,
  width_grid = 1,
  size_center_dot = 1){

  coord <- coord_items(
    data = data,
    rotate_radians = rotate_radians,
    rotate_degrees = rotate_degrees,
    dodge_axes = dodge_axes,
    width_items = width_items,
    length_items = length_items,
    length_ratio_items = length_ratio_items,
    rotate_title_radians =rotate_title_radians,
    rotate_title_degrees = rotate_title_degrees)

  myipv <- plot_items(
    coord = coord,
    size = size,
    filename = filename,
    filewidth = filewidth,
    fileheight = fileheight,
    dpi = dpi,
    colour = colour,
    colour2 = colour2,
    fade = fade,
    font = font,
    tick_label = tick_label,
    size_tick_label = size_tick_label,
    size_title = size_title,
    size_facet_labels = size_facet_labels,
    width_axes = width_axes,
    size_arrow_heads = size_arrow_heads,
    width_items = width_items,
    width_grid = width_grid,
    size_center_dot = size_center_dot)

  return(myipv)
}
