#' Plot Items
#'
#' Plots an item chart, showing the items of a test arranged by facets.
#'
#' @param coord list generated by \code{\link{coord_items}} or
#'   \code{\link{coord_nested}}.
#' @param size integer; smartly scaled size of chart objects except item bars.
#' @param filename character; name of the file to save. Supported formats are:
#'   "pdf" (best quality with lowest file size), "png", "jpeg". Use "none" to
#'   suppress file output; defaults to "myipv.pdf".
#' @param filewidth integer; width of the .pdf document; defaults to 12.
#' @param fileheight integer; height of the .pdf document; defaults to 10.
#' @param dpi integer; resolution in dots per inch; defaults to 500.
#' @param font character; text font; defaults to 'sans' (use extrafonts to
#'   install additional fonts).
#' @param colour character; name of the first accent colour.
#' @param colour2 character; name of the second accent colour.
#' @param fade integer; brightness of minor grid lines, gray tones between 0
#'   (black) and 100 (white) in steps of 1; defaults to 85.
#' @param tick_label logical; if \code{TRUE}, draws a text label for the axis
#'   tick
#' @param size_title integer; font size of the test label (relative to default).
#' @param size_facet_labels integer; font size of the axis labels (relative to
#'   default).
#' @param width_axes integer; width of the radial axis lines indicating center
#'   distances (relative to default).
#' @param size_arrow_heads integer; length of the arrow heads at the end of the
#'   axes (relative to default).
#' @param width_items integer; width of the item bars (relative to default).
#' @param width_grid integer; width of the dotted grid lines (relative to
#'   default).
#' @param size_tick_label integer; font size of the axis tick label (relative to
#'   default).
#' @param size_center_dot integer; size of the center dot marking the origin
#'   (relative to default).
#'
#' @details Use this function in conjunction with \code{\link{coord_items}} or
#'   \code{\link{coord_nested}} for simple models.
#'
#'   Use \code{\link{item_chart}} to create the chart in a single step.
#'
#'   Rotate using \code{\link{coord_items}}, not this function.
#'
#'   When changing the size of objects, consider the \code{size} parameter first
#'   and make specific adjustments with the other \code{size_} and \code{width_}
#'   parameters after.
#'
#'   To better display overlapping item values, change the width of the item
#'   bars, or set the accent colours to different values, or change the ratio of
#'   item lengths.
#'
#' @return Object of the class "ggplot" and optionally the same object saved as
#'   a file.
#'
#' @seealso \code{\link{coord_items}} \code{\link{item_chart}}
#'
#' @examples
#' # # creating item charts is a two step process, using coord_items and this
#' # # function:
#' # coord <- coord_items(DSSEI)
#' # DSSEI_items <- plot_items(coord, filename = "DSSEI_items.pdf")
#' # DSSEI_items
plot_items <- function (
  coord,
  size = 1,
  filename = "myipv.pdf",
  filewidth = 12,
  fileheight = 10,
  dpi = 500,
  colour = "black",
  colour2 = "black",
  fade = 85,
  font = "sans",
  tick_label = TRUE,
  size_tick_label = 1,
  size_title = 1,
  size_facet_labels = 1,
  width_axes = 1,
  size_arrow_heads = 1,
  width_items = 1,
  width_grid = 1,
  size_center_dot = 1) {


  # preparation ----------------------------------------------------------------

  # calculations are not possible within aes_string(), so aesthetics are
  # prepared here
  axis_labels <- row.names(coord$c_axes)


  # chart ----------------------------------------------------------------------

  myipv <- ggplot2::ggplot(coord$c_axes) + # x has placeholder value


    ## initializing -----------------

    ggplot2::coord_fixed() +
    ggplot2::theme(
      axis.line        = ggplot2::element_blank(),
      axis.text.x      = ggplot2::element_blank(),
      axis.text.y      = ggplot2::element_blank(),
      axis.ticks       = ggplot2::element_blank(),
      axis.title.x     = ggplot2::element_blank(),
      axis.title.y     = ggplot2::element_blank(),
      legend.position  = "none",
      panel.background = ggplot2::element_blank(),
      panel.border     = ggplot2::element_blank(),
      panel.grid.major = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      plot.background  = ggplot2::element_blank(),
      text             = ggplot2::element_text(size = 16, family = font),
      plot.margin      = ggplot2::margin(0, 0, 0, 0, "in")) +
    ggplot2::aes() +


    ## layers -----------------------

  # layers ordered from bottom to top

    # center dot
    ggplot2::geom_point(
      ggplot2::aes(x = 0, y = 0),
      size = .5 * size * size_center_dot) +

    # minor grid
    ggforce::geom_circle(
      data = coord$maingrid[coord$maingrid$alpha == .5, ],
      ggplot2::aes_string(x0 = "x", y0 = "y", r = "r"),
      color = paste("gray", fade, sep = ""),
      linetype = "dotted",
      size = sqrt(size) * min(c(size, .6)) * width_grid) +

    # major grid
    ggforce::geom_circle(
      data = coord$maingrid[coord$maingrid$alpha == 1, ],
      ggplot2::aes_string(x0 = "x", y0 = "y", r = "r"),
      color = "gray20",
      linetype = "dotted",
      size = sqrt(size) * min(c(size, .7)) * width_grid) +

    # axes
    ggplot2::geom_segment(
      data = coord$c_axes,
      ggplot2::aes_string(x = 0, y = 0, xend = "x", yend = "y"),
      arrow = ggplot2::arrow(
        ends = "last",
        length = ggplot2::unit(.02*sqrt(size) * size_arrow_heads, "native"),
        type = "closed"),
      size = .6 * sqrt(size) * width_axes) +

    # items 2
    ggplot2::geom_segment(
      data = coord$items[coord$items$length == max(coord$items$length), ],
      ggplot2::aes_string(x = "x1", y = "y1", xend = "x2", yend = "y2"),
      size = 1.5 * width_items,
      color = colour2) +

    # items 1
    ggplot2::geom_segment(
      data = coord$items[coord$items$length == min(coord$items$length), ],
      ggplot2::aes_string(x = "x1", y = "y1", xend = "x2", yend = "y2"),
      size = 1.5 * width_items,
      color = colour) +

    # title
    ggplot2::geom_text(
      data = coord$title,
      ggplot2::aes_string(x = "x", y = "y", label = "label"),
      family = font,
      size = 8 * sqrt(size) * size_title,
      color = colour,
      fontface = "bold") +

    # axis labels
    ggplot2::geom_text(
      ggplot2::aes_string(x = "xlabel", y = "ylabel", label = "axis_labels"),
      family = font,
      size = 6 * sqrt(size) * size_facet_labels,
      hjust = "inward")


  ## optional layers ----------------

  # tick label
  if(tick_label == TRUE) {
    myipv <- myipv +
      ggplot2::geom_text(
        data = coord$axis_tick[coord$axis_tick$rho < max(coord$maingrid$r), ],
        ggplot2::aes_string(x = "x", y = "y", label = "label"),
        angle =
          (coord$axis_tick[coord$axis_tick$rho <
                             max(coord$maingrid$r), "phi"] -
             pi / 48 - pi / 2) * 180 / pi,
        family = font,
        size = 3 * sqrt(size) * size_tick_label,
        color = "gray20")
  }


  # optional file save ---------------------------------------------------------

  ## .pdf ---------------------------

  if (substring(filename, nchar(filename)-3+1) == "pdf") {
    ggplot2::ggsave(filename,
                    myipv,
                    width = filewidth,
                    height = fileheight,
                    units = "in",
                    dpi = dpi)
  }


  ## .png ---------------------------

  if (substring(filename, nchar(filename)-3+1) == "png") {
    ggplot2::ggsave(filename,
                    myipv,
                    width = filewidth,
                    height = fileheight,
                    units = "in",
                    dpi = dpi)
  }


  ## .jpeg --------------------------

  if (substring(filename, nchar(filename)-3+1) == "peg") {
    ggplot2::ggsave(filename,
                    myipv,
                    width = filewidth,
                    height = fileheight,
                    units = "in",
                    dpi = dpi)
  }


  # return ---------------------------------------------------------------------

  return(myipv)
}
