#' Plot Nested
#'
#' Plots a nested chart, showing several tests and their facets in a global
#' chart.
#'
#' @param coord list generated by \code{\link{coord_nested}}.
#' @param size integer; smartly scaled size of chart objects.
#' @param filename character; name of the file to save. Supported formats are:
#'   "pdf" (best quality with lowest file size), "png", "jpeg". Use "none" to
#'   suppress file output; defaults to "myipv.pdf".
#' @param filewidth integer; width of the .pdf file; defaults to 10, dpi is
#'   3000.
#' @param fileheight integer; height of the .pdf file; defaults to 10, dpi is
#'   3000.
#' @param cor_labels_tests logical; if \code{TRUE}, draws latent correlations
#'   between tests as text.
#' @param cor_labels_facets logical; if \code{TRUE}, draws latent correlations
#'   between facets as text.
#' @param colour_tests character; name of the global accent colour.
#' @param colour_facets character; name of the nested accent colour.
#' @param fade integer; brightness of the gray tones between 0 (black) and 100
#'   (white) in steps of 1; defaults to 85.
#' @param show_xarrows logical; if \code{TRUE}, draws correlation arrows between
#'   facets of different tests.
#' @param tick numeric; axis tick position; defaults to .1.
#' @param font character; text font; defaults to 'sans' (use extrafonts to
#'   install additional fonts).
#' @param size_title integer; font size of the global label (relative to
#'   default).
#' @param size_test_labels integer; font size of the test labels (relative to
#'   default).
#' @param size_facet_labels integer; font size of the facet labels (relative to
#'   default).
#' @param width_axes integer; width of the global radial axis lines indicating
#'   center distances (relative to default).
#' @param width_axes_inner integer; width of the nested radial axis lines
#'   indicating center distances (relative to default).
#' @param width_circles integer; width of the global circle outlines (relative
#'   to default).
#' @param width_circles_inner integer; width of the nested circle outlines
#'   (relative to default).
#' @param width_tick integer; width of the global dotted axis tick line
#'   (relative to default).
#' @param width_tick_inner integer; width of the nested dotted axis tick line
#'   (relative to default).
#' @param size_tick_label integer; font size of the axis tick label (relative to
#'   default).
#' @param size_cor_labels integer; font size of the latent correlations between
#'   tests (relative to default).
#' @param size_cor_labels_inner integer; font size of the latent correlations
#'   between facets (relative to default).
#' @param size_center_dot integer; size of the center dot marking the global
#'   origin (relative to default).
#' @param size_center_dot_inner integer; size of the center dots marking the
#'   nested origins (relative to default).
#' @param width_xarrows integer; width of the extra arrow lines (relative to
#'   default).
#' @param size_xarrow_heads integer; length of the extra arrow heads (relative
#'   to default).
#' @param size_xarrow_labels integer; font size of the latent correlations
#'   indicated by extra arrows (relative to default).
#'
#' @details Use this function in conjunction with \code{\link{coord_nested}} for
#'   nested models.
#'
#'   Use \code{\link{nested_chart}} to create the chart in a single step.
#'
#'   The following changes to the chart appearance are made using
#'   \code{\link{coord_nested}}, not this function: \itemize{ \item overall
#'   rotation \item rotation of nested charts \item title repositioning \item
#'   circle radius \item relative scaling \item size of space for correlations }
#'
#'   When changing the size of objects, consider the \code{size} parameter first
#'   and make specific adjustments with the other \code{size_} and \code{width_}
#'   parameters after.
#'
#'   The nested chart treats tests like facets of a global factor. It uses facet
#'   charts for tests similar to how facet charts use circles for facets.
#'
#'   To add xarrows, you need to provide additional information to
#'   \code{\link{coord_nested}}.
#'
#' @return Object of the class "ggplot" and optionally the same object saved as
#'   a file.
#'
#' @seealso \code{\link{coord_nested}} \code{\link{nested_chart}}
#'
#' @examples
#' # # creating nested charts is a two step process, using coord_nested and this
#' # # function:
#' # coord <- coord_nested(self_confidence, subradius = .6)
#' # sc_nested <- plot_nested(coord, filename = "sc_nested.pdf")
#' # sc_nested
#'#
#' # # adding xarrows
#' # sc_arrows <- data.frame(test1 = rep(NA, 3),
#'#                          facet1 = NA,
#'#                          test2 = NA,
#'#                          facet2 = NA,
#'#                          value = NA)
#' # sc_arrows[1, ] <- c("DSSEI", "Ab", "RSES", "Ps", ".67")
#' # sc_arrows[2, ] <- c("DSSEI", "Ab", "SMTQ", "Cs", ".81")
#' # sc_arrows[3, ] <- c("SMTQ", "Ct", "RSES", "Ns", ".76")
#' # coord <- coord_nested(self_confidence, subradius = .6, xarrows = sc_arrows)
#' # sc_nested <- plot_nested(coord, filename = "sc_nested.pdf", show_xarrows = TRUE)
#' # sc_nested
plot_nested <- function (
  coord,
  size = 1,
  filename = "myipv.pdf",
  filewidth = 10,
  fileheight = 10,
  cor_labels_tests = TRUE,
  cor_labels_facets = TRUE,
  colour_tests = "black",
  colour_facets = "black",
  fade = 85,
  font = "sans",
  show_xarrows = FALSE,
  tick = .1,
  size_title = 1,
  size_test_labels = 1,
  size_facet_labels = 1,
  width_axes = 1,
  width_axes_inner = 1,
  width_circles = 1,
  width_circles_inner = 1,
  width_tick = 1,
  width_tick_inner = 1,
  size_tick_label = 1,
  size_cor_labels = 1,
  size_cor_labels_inner = 1,
  size_center_dot = 1,
  size_center_dot_inner = 1,
  width_xarrows = 1,
  size_xarrow_heads = 1,
  size_xarrow_labels = 1) {


  # preparation ----------------------------------------------------------------

  # correlations
  if (cor_labels_tests == TRUE) {
    cors <- coord$g$cors
  } else cors <- NULL

  # subfactor correlations
  if (cor_labels_facets == TRUE) {
    cors_inner <- coord$g$nested$cors
  } else cors_inner <- NULL


  # chart ----------------------------------------------------------------------

  myipv <- ggplot2::ggplot(coord$g$c_circs) +


    ## initializing -----------------

    ggplot2::coord_fixed() +
    ggplot2::theme(
      axis.line        = ggplot2::element_blank(),
      axis.text.x      = ggplot2::element_blank(),
      axis.text.y      = ggplot2::element_blank(),
      axis.ticks       = ggplot2::element_blank(),
      axis.title.x     = ggplot2::element_blank(),
      axis.title.y     = ggplot2::element_blank(),
      legend.position  = "none",
      panel.background = ggplot2::element_blank(),
      panel.border     = ggplot2::element_blank(),
      panel.grid.major = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      plot.background  = ggplot2::element_blank(),
      text             = ggplot2::element_text(size = 16, family = font),
      plot.margin      = ggplot2::margin(0, 0, 0, 0, "in")) +
    ggplot2::aes() +


    ## layers -----------------------

    # layers ordered from bottom to top

    # tick label
    ggplot2::geom_text(
      data = coord$g$axis_tick,
      ggplot2::aes(x = coord$g$rs * (x * tick + sign(x) * .02),
                   y = coord$g$rs * (y * tick + sign(y) * .02),
                   label = as.character(tick)),
      angle = (coord$g$axis_tick$phi - pi / 48 - pi / 2) * 180 / pi,
      family = font,
      size = 1.95 * sqrt(size) * size_tick_label) +

    # global tick
    ggforce::geom_circle(
      ggplot2::aes(x0 = 0, y0 = 0, r = coord$g$rs * tick),
      linetype = "dotted",
      size = coord$g$rs * .5 * min(c(size, .25)) * width_tick) +

    # global outer axis segments
    ggplot2::geom_segment(
      data = coord$g$c_axes,
      ggplot2::aes(x = x2, y = y2, xend = x3, yend = y3),
      size = .5 * size * width_axes,
      color = paste("gray", fade, sep = "")) +

    # global circle
    ggforce::geom_circle(
      data = coord$g$c_circs[1, ],
      ggplot2::aes(x0 = x, y0 = y, r = radius),
      size = .5 * size * width_axes,
      color = paste("gray", fade, sep = "")) +

    # global center dot
    ggplot2::geom_point(
      ggplot2::aes(x = 0, y = 0),
      size = 5 * sqrt(size) * size_center_dot) +

    # nested outer axis segments
    ggplot2::geom_segment(
      data = coord$g$nested$axes,
      ggplot2::aes(x = x2, y = y2, xend = x3, yend = y3),
      size = .3 * size * width_axes_inner,
      color = paste("gray", fade, sep = "")) +

    # nested center dots
    ggplot2::geom_point(
      data = coord$g$c_circs,
      ggplot2::aes(x = x, y = y),
      size = 2.5 * sqrt(size) * size_center_dot_inner) +

    # test circles
    ggforce::geom_circle(
      data = coord$g$c_circs[-1, ],
      ggplot2::aes(x0 = x, y0 = y, r = radius),
      size = .5 * size * width_circles,
      color = colour_tests) +

    # nested tick
    ggforce::geom_circle(
      data = coord$g$c_circs[-1, ],
      ggplot2::aes(x0 = x, y0 = y, r = tick),
      size = 0.5 * min(c(size, .25)) * width_tick_inner,
      linetype = "dotted") +

    # global inner axis segments
    ggplot2::geom_segment(
      data = coord$g$c_axes,
      ggplot2::aes(x = x0, y = y0, xend = x1, yend = y1),
      size = .5 * (sqrt(size) + size) * width_axes,
      color = colour_tests) +

    # facet circles
    ggforce::geom_circle(
      data = coord$g$nested$circles,
      ggplot2::aes(x0 = x, y0 = y, r = radius),
      size = .25 * size * width_circles_inner,
      color = colour_facets) +

    # facet labels
    ggplot2::geom_text(
      data = coord$g$nested$circles,
      ggplot2::aes(x, y, label = label),
      family = font,
      size = 3.125 * sqrt(size) * size_facet_labels) +

    # nested inner axis segments
    ggplot2::geom_segment(
      data = coord$g$nested$axes,
      ggplot2::aes(x = x0, y = y0, xend = x1, yend = y1),
      size = .25 * (sqrt(size) + size) * width_axes_inner,
      color = colour_facets) +

    # title
    ggplot2::geom_text(
      data = coord$g$title,
      ggplot2::aes(x = x, y = y, label = label),
      family = font,
      size = 16 / 3 * sqrt(size) * size_title,
      fontface = "bold") +

    # test labels
    ggplot2::geom_text(
      data = coord$g$nested$title,
      ggplot2::aes(x = x, y = y, label = label),
      family = font,
      size = 4 * sqrt(size) * size_test_labels,
      fontface = "bold")


  ## optional layers ----------------

  # facet correlations
  if (!is.null(cors_inner)) {
    myipv <- myipv +
      ggplot2::geom_text(
        data = cors_inner,
        ggplot2::aes(x = x, y = y, label = label),
        family = font,
        size = 2.25 * sqrt(size) * size_cor_labels_inner)
  }

  # test correlations
  if (!is.null(cors)) {

    # rings
    # c() enables putting layer on the bottom
    myipv$layers <- c(
      ggforce::geom_circle(
        data = coord$g$c_ring,
        ggplot2::aes(x0 = x, y0 = y, r = radius),
        size = .3 * size * width_axes_inner,
        color = paste("gray", fade, sep = "")),
      myipv$layers)

    # labels
    myipv <-  myipv +
      ggplot2::geom_text(
        data = cors,
        ggplot2::aes(x = x, y = y, label = label),
        family = font,
        size = coord$g$cor_spacing * 6.75 * sqrt(size) * size_cor_labels,
        fontface = "bold")
  }

  # extra arrows
  if (show_xarrows == TRUE) {
    myipv <- myipv +

      # arrows
      ggplot2::geom_segment(
        data = coord$g$arrows,
        ggplot2::aes(x = x1, y = y1, xend = x2, yend = y2),
        arrow = ggplot2::arrow(
          ends = "both",
          length = ggplot2::unit(.003 * sqrt(size) * size_xarrow_heads,
                                 "native"),
          type = "closed"),
        size = .25 * size * width_xarrows,
        linetype = "dotted",
        color = "gray20") +

      # labels
      ggplot2::geom_text(
        data = coord$g$arrows,
        ggplot2::aes(x = xlabel, y = ylabel, label = label),
        size = 2.25 * sqrt(size) * size_xarrow_labels,
        family = font,
        color = "gray20")
  }


  # optional file save ---------------------------------------------------------

  ## .pdf ---------------------------

  if (substring(filename, nchar(filename)-3+1) == "pdf") {
    ggplot2::ggsave(filename,
                    myipv,
                    width = filewidth,
                    height = fileheight,
                    units = "in",
                    dpi = 3000)
  }


  ## .png ---------------------------

  if (substring(filename, nchar(filename)-3+1) == "png") {
    ggplot2::ggsave(filename,
                    myipv,
                    width = filewidth,
                    height = fileheight,
                    units = "in",
                    dpi = 500)
  }


  ## .jpeg --------------------------

  if (substring(filename, nchar(filename)-3+1) == "peg") {
    ggplot2::ggsave(filename,
                    myipv,
                    width = filewidth,
                    height = fileheight,
                    units = "in",
                    dpi = 500)
  }


  # return ---------------------------------------------------------------------

  return(myipv)
}
