#' Plot Items
#'
#' Plots an item chart, showing the items of a test arranged by facets.
#'
#' @param coor list generated by \code{\link{coord_items}} or
#'   \code{\link{coord_nested}}.
#' @param size integer; smartly scaled size of chart objects.
#' @param filesave logical, if TRUE, saves the chart to the working directory as
#'   [filename].pdf
#' @param filename character string; name of the .pdf file the chart is written
#'   to; filename extension added automatically: [filename].pdf.
#' @param filewidth integer; width of the .pdf document; defaults to 10; dpi is
#'   3000.
#' @param fileheight integer; height of the .pdf document; defaults to 10, dpi
#'   is 3000.
#' @param font character; text font; defaults to 'sans' (use extrafonts to
#'   install additional fonts).
#' @param colour character; name of the first accent colour.
#' @param colour2 character; name of the second accent colour.
#' @param fade integer; brightness of minor grid lines, gray tones between 0
#'   (black) and 100 (white) in steps of 1; defaults to 90.
#' @param tick_label logical; if \code{TRUE}, draws a text label for the axis
#'   tick
#' @param size_title integer; font size of the test label (relative to default).
#' @param size_axis_labels integer; font size of the axis labels (relative to
#'   default).
#' @param width_axes integer; width of the radial axis lines (relative to
#'   default).
#' @param size_arrow_heads integer; length of the arrow heads (relative to
#'   default).
#' @param width_items integer; width of the item bars (relative to default).
#'   Currently not supported!
#' @param width_grid integer; width of the dotted grid lines (relative to
#'   default).
#' @param size_tick_label integer; font size of the axis tick label (relative to
#'   default).
#' @param size_center_dot integer; size of the center dot marking the origin
#'   (relative to default).
#'
#' @details Use this function in conjunction with \code{\link{coord_items}} or
#'   \code{\link{coord_nested}} for simple models.
#'
#'   To better display overlapping item values, set the accent colours to
#'   different values.
#'
#' @return Object of the class "ggplot" and the same object as a .pdf file.
#'
#' @seealso \code{\link{coord_items}}
#'
#' @examples
#' # creating item charts is a two step process, using coord_items and this function:
#' coord <- coord_items(DSSEI)
#' DSSEI_items <- plot_items(coord,filename = "DSSEI_items")
#' DSSEI_items
#'
#' @export
plot_items <- function(coor,size=1,filesave=TRUE,filename=NULL,
                            filewidth=10,fileheight=10,font="sans",
                            colour="black",colour2="black",fade=90,tick_label=TRUE,
                            size_title=1,size_axis_labels=1,width_axes=1,size_arrow_heads=1,width_items=1,width_grid=1,size_tick_label=1,size_center_dot=1){

  # empty filename warning
  if(filesave==TRUE && is.null(filename))warning("empty filename")

  # chart layers
  myfbrv <- ggplot2::ggplot(coor$cart_axes)+
    ggplot2::geom_text(ggplot2::aes(x=xlabel,y=ylabel,label = row.names(coor$cart_axes)),family = font,size = 6*sqrt(size)*size_axis_labels,hjust = "inward")+
    ggplot2::coord_fixed()+
    ggplot2::theme_minimal()+
    ggplot2::aes()+
    ggplot2::geom_point(ggplot2::aes(x=0,y=0),size=.5*size*size_center_dot)+
    ggforce::geom_circle(data = coor$maingrid[coor$maingrid$alpha==.5,],ggplot2::aes(x0=x,y0=y,r=r),col = paste("gray",fade,sep = ""),linetype = "dotted",size=min(c(size,.75))*width_grid)+
    ggforce::geom_circle(data = coor$maingrid[coor$maingrid$alpha==1,],ggplot2::aes(x0=x,y0=y,r=r),col = "gray20",linetype = "dotted",size=min(c(size,.75))*width_grid)+
    ggplot2::geom_segment(data = coor$cart_axes,ggplot2::aes(x=0,y=0,xend=x,yend=y),arrow = ggplot2::arrow(ends = "last",length = ggplot2::unit(.02*sqrt(size)*size_arrow_heads,"native"),type = "closed"),size=.5*sqrt(size)*width_axes)+
    ggplot2::geom_segment(data = coor$items[coor$items$width==max(coor$items$width),],ggplot2::aes(x=x1,y=y1,xend=x2,yend=y2),size=1,col = colour2)+
    ggplot2::geom_segment(data = coor$items[coor$items$width==min(coor$items$width),],ggplot2::aes(x=x1,y=y1,xend=x2,yend=y2),size=1,col = colour)+
    # width_items currently not supported since it shifts the edge of the bars away from the correct position determined by the center distance
    # ggplot2::geom_segment(data = coor$items,ggplot2::aes(x=x1,y=y1,xend=x2,yend=y2),size=size*width_items,col = colour)+
    ggplot2::geom_text(data = coor$factor_label,ggplot2::aes(x=x,y=y,label = label),family = font,size = 6*sqrt(size)*size_title,col=colour,fontface="bold")+
    ggplot2::theme(axis.line=ggplot2::element_blank(),axis.text.x=ggplot2::element_blank(),axis.text.y=ggplot2::element_blank(),axis.ticks=ggplot2::element_blank(),
          axis.title.x=ggplot2::element_blank(),axis.title.y=ggplot2::element_blank(),legend.position = "none",
          panel.background=ggplot2::element_blank(),panel.border=ggplot2::element_blank(),panel.grid.major=ggplot2::element_blank(),
          panel.grid.minor=ggplot2::element_blank(),plot.background=ggplot2::element_blank(),text = ggplot2::element_text(size = 16,family = font),plot.margin = ggplot2::margin(1,1,1,1,"in"))

  # adding tick label (optional)
  if(tick_label == TRUE && max(coor$maingrid$r)>=.5) myfbrv <- myfbrv +  ggplot2::geom_text(data = coor$axis_tick,ggplot2::aes(x,y,label = label),angle = (coor$axis_tick$phi-pi/48-pi/2)*180/pi,family = font,size = 3*sqrt(size)*size_tick_label,col = "gray20")

  # saving as .pdf file
  if(filesave == TRUE) ggplot2::ggsave(paste(filename,".pdf",sep = ""),myfbrv,width = filewidth ,height = fileheight, units = "in",dpi = 3000)

  return(myfbrv)
}
