#' Plot Facets
#'
#' This function plots a factor and its facets as circles.
#'
#' @param coor list generated by \code{\link{model_facets}} or \code{\link{model_nested}} containing the coordinates of the parts of the plot.
#' @param size integer; smartly scaled size of all parts of the plot.
#' @param filename character string; name of the .pdf file the plot is written to; filename extension adds automatically.
#' @param width integer; width of the .pdf file; defaults to 10.
#' @param height integer; height of the .pdf file; defaults to 10.
#' @param colour character; name of the accent colour.
#' @param cor_labels logical; if TRUE, plots latent correlations between facets as text.
#' @param tick numeric; axis tick position; defaults to .1.
#' @param font character; text font; defaults to 'Helvetica' (use extrafonts to install fonts you do not have).
#' @param size_title integer; font size of the factor label (relative to default).
#' @param size_subfactor_labels integer; font size of the subfactor label (relative to default).
#' @param width_axes integer; width of the radial axis lines (relative to default).
#' @param width_circles integer; width of the circle outlines (relative to default).
#' @param size_tick integer; width of the dotted axis tick line (relative to default).
#' @param size_tick_label integer; font size of the axis tick label (relative to default).
#' @param size_cor_labels integer; font size of the latent correlations between facets (relative to default).
#' @param size_center_dot integer; size of the center dot marking the origin (relative to default).
#'
#' @details Facets are displayed using the average center distance of their items
#' as distance from the origin to the circle's edge.
#'
#' @return an object of the class "ggplot" and the same object as a .pdf file.
#'
#' @seealso \code{\link{model_facets}}
#'
#' @examples
#' # creating plots is a two step process, using model_ and plot_ functions:
#' coord <- model_facets(DSSEI,subradius = .5)
#' DSSEI_item_plot <- plot_facets(coord,filename = "DSSEI_facets")
#'
#' @export
plot_facets <- function(coor,size=1,filename,
                      width=10,height=10,colour="black",cor_labels=TRUE,tick=.1,font="Helvetica",
                      size_title=1,size_subfactor_labels=1,width_axes=1,width_circles=1,size_tick=1,size_tick_label=1,size_cor_labels=1,size_center_dot=1){

  # preparing cor labels
  if(cor_labels==TRUE){
    inner_cors <- coor$inner_cors
  }
  else inner_cors <- NULL

  # plot layers
  myfbrv <- ggplot2::ggplot(coor$cart_circles)+
    ggplot2::geom_point(ggplot2::aes(x=0,y=0),size=5*sqrt(size)*size_center_dot)+
    ggforce::geom_circle(ggplot2::aes(x0=0,y0=0,r=tick),linetype = "dotted",size=.5*min(c(size,.5))*size_tick)+
    ggplot2::geom_segment(data = coor$cart_axes,ggplot2::aes(x=x2,y=y2,xend=x3,yend=y3),size=size*width_axes,color="gray90")+
    ggplot2::geom_text(ggplot2::aes(x,y,label = row.names(coor$cart_circles)),family = font,size = 8*sqrt(size)*size_subfactor_labels)+
    ggplot2::coord_fixed()+
    ggplot2::theme_minimal()+
    ggplot2::aes()+
    ggplot2::geom_text(data=coor$axis_tick,ggplot2::aes(x=x*tick+sign(x)*.02,y=y*tick+sign(y)*.02,label=as.character(tick)),angle = (coor$axis_tick$phi-pi/48-pi/2)*180/pi,family = font,size = 2*sqrt(size)*size_tick_label)+
    ggforce::geom_circle(data=coor$cart_circles[1,],ggplot2::aes(x0=x,y0=y,r=radius),size=size*width_axes,color="gray90")+
    ggforce::geom_circle(data=coor$cart_circles[-1,],ggplot2::aes(x0=x,y0=y,r=radius),size=size*width_circles,color=colour)+
    ggplot2::geom_segment(data = coor$cart_axes,ggplot2::aes(x=x0,y=y0,xend=x1,yend=y1),size=(sqrt(size)+size)*width_axes,col=colour)+
    ggplot2::geom_text(data = coor$factor_label,ggplot2::aes(x=x,y=y,label=label),family = font,size = 8*sqrt(size)*size_title,fontface="bold")+
    ggplot2::theme(axis.line=ggplot2::element_blank(),axis.text.x=ggplot2::element_blank(),axis.text.y=ggplot2::element_blank(),axis.ticks=ggplot2::element_blank(),
          axis.title.x=ggplot2::element_blank(),axis.title.y=ggplot2::element_blank(),legend.position = "none",
          panel.background=ggplot2::element_blank(),panel.border=ggplot2::element_blank(),panel.grid.major=ggplot2::element_blank(),
          panel.grid.minor=ggplot2::element_blank(),plot.background=ggplot2::element_blank(),text = ggplot2::element_text(size = 16,family = font),plot.margin = ggplot2::margin(1,1,1,1,"in"))

  # adding cor labels (optional)
  if(!is.null(inner_cors))myfbrv <- myfbrv +
    ggplot2::geom_text(data = inner_cors,ggplot2::aes(x=x,y=y,label=label),family = font,size = 4*sqrt(size)*size_cor_labels)

  # saving as .pdf file
  ggplot2::ggsave(paste(filename,".pdf",sep = ""),myfbrv,width = width ,height = height, units = "in",dpi = 3000)

  return(myfbrv)
}
