#' Plot Nested
#'
#' Plots a nested chart, showing several tests and their facets in a global
#' chart.
#'
#' @param coor list generated by \code{\link{coord_nested}}.
#' @param size integer; smartly scaled size of chart objects.
#' @param filename character string; name of the .pdf file the chart is written
#'   to; filename extension adds automatically.
#' @param width integer; width of the .pdf file; defaults to 10, dpi is 3000.
#' @param height integer; height of the .pdf file; defaults to 10, dpi is 3000.
#' @param cor_labels logical; if \code{TRUE}, draws latent correlations between
#'   tests as text.
#' @param subfactor_cor_labels logical; if \code{TRUE}, draws latent
#'   correlations between facets as text.
#' @param colour character; name of the global accent colour.
#' @param subcolour character; name of the nested accent colour
#' @param extra_arrows logical; if \code{TRUE}, draws correlation arrows between
#'   facets of different tests.
#' @param tick numeric; axis tick position; defaults to .1.
#' @param font character; text font; defaults to 'sans' (use extrafonts to
#'   install additional fonts).
#' @param size_title integer; font size of the global label (relative to
#'   default).
#' @param size_subfactor_labels integer; font size of the test labels (relative
#'   to default).
#' @param size_subfactor_labels_inner integer; font size of the facet labels
#'   (relative to default).
#' @param width_axes integer; width of the global radial axis lines (relative to
#'   default).
#' @param width_axes_inner integer; width of the nested radial axis lines
#'   (relative to default).
#' @param width_circles integer; width of the global circle outlines (relative
#'   to default).
#' @param width_circles_inner integer; width of the nested circle outlines
#'   (relative to default).
#' @param size_tick integer; width of the global dotted axis tick line (relative
#'   to default).
#' @param size_tick_inner integer; width of the nested dotted axis tick line
#'   (relative to default).
#' @param size_tick_label integer; font size of the axis tick label (relative to
#'   default).
#' @param size_cor_labels integer; font size of the latent correlations between
#'   tests (relative to default).
#' @param size_cor_labels_inner integer; font size of the latent correlations
#'   between facets (relative to default).
#' @param size_center_dot integer; size of the center dot marking the global
#'   origin (relative to default).
#' @param size_center_dot_inner integer; size of the center dots marking the
#'   nested origins (relative to default).
#' @param size_extra_arrows integer; width of the extra arrow lines (relative to
#'   default).
#' @param size_extra_arrow_heads integer; length of the extra arrow heads
#'   (relative to default).
#' @param size_extra_labels integer; font size of the latent correlations
#'   indicated by extra arrows (relative to default).
#'
#' @details Use this function in conjunction with \code{\link{coord_nested}} for
#'   nested models.
#'
#'   The nested chart treats tests like facets of a global factor. It uses facet
#'   charts for tests similar to how facet charts use circles for facets.
#'
#'   Rotate by changing your \code{\link{coord_nested}} function call.
#'
#'   To add extra_arrows, you need to provide additional information to
#'   \code{\link{coord_nested}}.
#'
#' @return Object of the class "ggplot" and the same object as a .pdf file.
#'
#' @seealso \code{\link{coord_nested}}
#'
#' @examples
#' # creating nested charts is a two step process, using coord_nested and this function:
#' coord <- coord_nested(self_confidence, subradius = .6)
#' sc_nested <- plot_nested(coord, filename = "sc_nested")
#'
#' # adding extra arrows
#' sc_arrows <- data.frame(V1_factor=rep(NA,3),
#'                         V1_subfactor=rep(NA,3),
#'                         V2_factor=rep(NA,3),
#'                         V2_subfactor=rep(NA,3),
#'                         value=rep(NA,3))
#' sc_arrows[1,] <- c("DSSEI","Ab","RSES","Ps",".67")
#' sc_arrows[2,] <- c("DSSEI","Ab","SMTQ","Cs",".81")
#' sc_arrows[3,] <- c("SMTQ","Ct","RSES","Ns",".76")
#' coord <- coord_nested(self_confidence,subradius = .6,extra_arrows = sc_arrows)
#' sc_plot <- plot_nested(coord,filename = "self_confidence_nested",extra_arrows = TRUE)
#' sc_plot
#'
#' @export
plot_nested <- function(coor,size=1,filename,width=10,height=10,
                      cor_labels=TRUE,subfactor_cor_labels=TRUE,
                      colour="black",subcolour="black",extra_arrows=FALSE,tick=.1,font="sans",
                      size_title=1,size_subfactor_labels=1,size_subfactor_labels_inner=1,width_axes=1,width_axes_inner=1,
                      width_circles=1,width_circles_inner=1,size_tick=1,size_tick_inner=1,size_tick_label=1,size_cor_labels=1,size_cor_labels_inner=1,
                      size_center_dot=1,size_center_dot_inner=1,size_extra_arrows=1,size_extra_arrow_heads=1,size_extra_labels=1){

    ## nested plot

  # preparing cor labels
  if(cor_labels==TRUE){
    inner_cors <- coor$global$inner_cors
  }
  else inner_cors <- NULL

  # preparing subfactor cor labels
  if(subfactor_cor_labels==TRUE){
    subfactor_inner_cors <- coor$global$nested$inner_cors
  }
  else subfactor_inner_cors <- NULL

  # plot layers
  globalplot <- ggplot2::ggplot(coor$global$cart_circles)+
    ggplot2::coord_fixed()+
    ggplot2::theme_minimal()+
    ggplot2::aes()+
    ggplot2::geom_text(data=coor$global$axis_tick,ggplot2::aes(x=coor$global$relative_scaling*(x*tick+sign(x)*.02),y=coor$global$relative_scaling*(y*tick+sign(y)*.02),label=as.character(tick)),angle = (coor$global$axis_tick$phi-pi/48-pi/2)*180/pi,family = font,size = 1.95*sqrt(size)*size_tick_label)+
    ggforce::geom_circle(ggplot2::aes(x0=0,y0=0,r=coor$global$relative_scaling*tick),linetype = "dotted",size=coor$global$relative_scaling*.5*min(c(size,.25))*size_tick)+
    ggplot2::geom_segment(data = coor$global$cart_axes,ggplot2::aes(x=x2,y=y2,xend=x3,yend=y3),size=.5*size*width_axes,color="gray90")+
    ggforce::geom_circle(data=coor$global$cart_circles[1,],ggplot2::aes(x0=x,y0=y,r=radius),size=.5*size*width_axes,color="gray90")+
    ggplot2::geom_point(ggplot2::aes(x=0,y=0),size=size*size_center_dot)+
    ggplot2::geom_segment(data = coor$global$nested$axes,ggplot2::aes(x=x2,y=y2,xend=x3,yend=y3),size=.3*size*width_axes_inner,color="gray90")+
    ggplot2::geom_point(data=coor$global$cart_circles,ggplot2::aes(x=x,y=y),size=.5*size*size_center_dot_inner)+
    ggforce::geom_circle(data=coor$global$cart_circles[-1,],ggplot2::aes(x0=x,y0=y,r=radius),size=.5*size*width_circles,color=colour)+
    ggforce::geom_circle(data=coor$global$cart_circles[-1,],ggplot2::aes(x0=x,y0=y,r=tick),size=0.5*min(c(size,.25))*size_tick_inner,linetype = "dotted")+
    ggplot2::geom_segment(data = coor$global$cart_axes,ggplot2::aes(x=x0,y=y0,xend=x1,yend=y1),size=.5*(sqrt(size)+size)*width_axes,color=colour)+
    ggforce::geom_circle(data=coor$global$nested$circles,ggplot2::aes(x0=x,y0=y,r=radius),size=.25*size*width_circles_inner,color=subcolour)+
    ggplot2::geom_text(data=coor$global$nested$circles,ggplot2::aes(x,y,label = label),family = font,size = 3.125*sqrt(size)*size_subfactor_labels_inner)+
    ggplot2::geom_segment(data = coor$global$nested$axes,ggplot2::aes(x=x0,y=y0,xend=x1,yend=y1),size=.25*(sqrt(size)+size)*width_axes_inner,color=subcolour)+
    ggplot2::geom_text(data = coor$global$factor_label,ggplot2::aes(x=x,y=y,label=label),family = font,size = 16/3*sqrt(size)*size_title,fontface="bold")+
    ggplot2::geom_text(data = coor$global$nested$factor_label,ggplot2::aes(x=x,y=y,label=label),family = font,size = 4*sqrt(size)*size_subfactor_labels,fontface="bold")+
    ggplot2::theme(axis.line=ggplot2::element_blank(),axis.text.x=ggplot2::element_blank(),axis.text.y=ggplot2::element_blank(),axis.ticks=ggplot2::element_blank(),
          axis.title.x=ggplot2::element_blank(),axis.title.y=ggplot2::element_blank(),legend.position = "none",
          panel.background=ggplot2::element_blank(),panel.border=ggplot2::element_blank(),panel.grid.major=ggplot2::element_blank(),
          panel.grid.minor=ggplot2::element_blank(),plot.background=ggplot2::element_blank(),text = ggplot2::element_text(size = 16,family = font),plot.margin = ggplot2::margin(1,1,1,1,"in"))

  # adding subfactor cor labels (optional)
  if(!is.null(subfactor_inner_cors)){globalplot <- globalplot +
    ggplot2::geom_text(data = subfactor_inner_cors,ggplot2::aes(x=x,y=y,label=label),family = font,size = 2.25*sqrt(size)*size_cor_labels_inner)}

  # adding cor labels (optional)
  if(!is.null(inner_cors)){globalplot$layers <- c(ggforce::geom_circle(data=coor$global$cart_inner_ring,ggplot2::aes(x0=x,y0=y,r=radius),size=.3*size*width_axes_inner,color="gray90"),globalplot$layers)
    globalplot <-  globalplot + ggplot2::geom_text(data = inner_cors,ggplot2::aes(x=x,y=y,label=label),family = font,size = coor$global$cor_spacing*6.75*sqrt(size)*size_cor_labels,fontface="bold")}

  # adding extra arrows (optional)
  if(extra_arrows==TRUE){globalplot <- globalplot +
    ggplot2::geom_segment(data = coor$global$arrows,ggplot2::aes(x=x1,y=y1,xend=x2,yend=y2),arrow = ggplot2::arrow(ends = "both",length = ggplot2::unit(.003*sqrt(size)*size_extra_arrow_heads,"native"),type = "closed"),size=.25*size*size_extra_arrows,linetype = "dotted",color="gray20")+
    ggplot2::geom_text(data = coor$global$arrows,ggplot2::aes(x=xlabel,y=ylabel,label=label),size=2.25*sqrt(size)*size_extra_labels,family=font,color="gray20")}

  # saving as .pdf file
  ggplot2::ggsave(paste(filename,".pdf",sep = ""),globalplot,width = width ,height = height, units = "in",dpi = 3000)

  return(globalplot)
}
