shift_factor <- function(data,x,y){
  # data is a to be shifted set of coordinates for a single factor as generated by fbrv.model
  # x is the x-shift, y is the y-shift to be applied
  # if expand is T, the shift will be much different as to make room for correlation labels
  
  # stripping off superfluous information
  data_shifted <- data[c("cart_circles",
                         "cart_axes",
                         "factor_label",
                         "inner_cors")]
  data_shifted$axis_tick[1:2] <- list(NULL)
  

  
  # adding x shift
  data_shifted$cart_circles$x <- data_shifted$cart_circles$x+x
  data_shifted$cart_axes$x0 <- data_shifted$cart_axes$x0+x
  data_shifted$cart_axes$x1 <- data_shifted$cart_axes$x1+x
  data_shifted$cart_axes$x2 <- data_shifted$cart_axes$x2+x
  data_shifted$cart_axes$x3 <- data_shifted$cart_axes$x3+x
  data_shifted$axis_tick$x <- data_shifted$axis_tick$x+x
  data_shifted$factor_label$x <- data_shifted$factor_label$x+x
  data_shifted$inner_cors$x <- data_shifted$inner_cors$x+x
  
  # adding y shift
  data_shifted$cart_circles$y <- data_shifted$cart_circles$y+y
  data_shifted$cart_axes$y0 <- data_shifted$cart_axes$y0+y
  data_shifted$cart_axes$y1 <- data_shifted$cart_axes$y1+y
  data_shifted$cart_axes$y2 <- data_shifted$cart_axes$y2+y
  data_shifted$cart_axes$y3 <- data_shifted$cart_axes$y3+y
  data_shifted$factor_label$y <- data_shifted$factor_label$y+y
  data_shifted$inner_cors$y <- data_shifted$inner_cors$y+y
  
  return(data_shifted)
  
}