#' Shift Factor
#' 
#' This function moves the coordinates given by \code{\link{model_facets}} to nest the facet plots in \code{\link{model_nested}}.
#'
#' @param data list generated by \code{\link{model_facets}} containing the coordinates of the parts of the plot.
#' @param x integer; horizontal shift.
#' @param y integer; vertical shift.
#'
#' @return A list of dataframes containing a limited selection of coordinates of plot objects.
shift_factor <- function(data,x,y){
  # stripping off superfluous information
  data_shifted <- data[c("cart_circles",
                         "cart_axes",
                         "factor_label",
                         "inner_cors")]
  data_shifted$axis_tick[1:2] <- list(NULL) # polar coordinates not needed anymore

  # adding x shift to all x coordinates
  data_shifted$cart_circles$x <- data_shifted$cart_circles$x+x
  data_shifted$cart_axes$x0 <- data_shifted$cart_axes$x0+x
  data_shifted$cart_axes$x1 <- data_shifted$cart_axes$x1+x
  data_shifted$cart_axes$x2 <- data_shifted$cart_axes$x2+x
  data_shifted$cart_axes$x3 <- data_shifted$cart_axes$x3+x
  data_shifted$axis_tick$x <- data_shifted$axis_tick$x+x
  data_shifted$factor_label$x <- data_shifted$factor_label$x+x
  data_shifted$inner_cors$x <- data_shifted$inner_cors$x+x
  
  # adding y shift to all y coordinates
  data_shifted$cart_circles$y <- data_shifted$cart_circles$y+y
  data_shifted$cart_axes$y0 <- data_shifted$cart_axes$y0+y
  data_shifted$cart_axes$y1 <- data_shifted$cart_axes$y1+y
  data_shifted$cart_axes$y2 <- data_shifted$cart_axes$y2+y
  data_shifted$cart_axes$y3 <- data_shifted$cart_axes$y3+y
  data_shifted$factor_label$y <- data_shifted$factor_label$y+y
  data_shifted$inner_cors$y <- data_shifted$inner_cors$y+y
  
  return(data_shifted)
}